name: CaSILE
on: [push, pull_request]
jobs:

  casile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CaSILE
        id: casile
        uses: sile-typesetter/casile@latest
        with:
          args: ["-dv", "make"]
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.casile.outputs.DISTDIR }}.zip
          path: ${{ steps.casile.outputs.DISTDIR }}/*
