name: CaSILE
on: [push, pull_request]
jobs:
  casile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: env
      - id: casile
        uses: sile-typesetter/casile@master
        with:
          args: -d make -- debug
