name: CaSILE
on: [push, pull_request]
jobs:
  casile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "DISTDIR=foobar" >> $GITHUB_ENV
      - id: casile
        uses: sile-typesetter/casile@master
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: foobar
          path: foobar/*
